# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f0e5c34e3e9506244f308b5b40ecbccc10555ed4f3826353611469b83da20fa7e55e6ddaf7c9b354bfeb6feeaf3a01ac5ba6c96c59d309a8978aa75a586972

test:
  secret_key_base: e946397ef2d90a7e897dc8ca3e5f41a40968cb7d87cf96ea58275809bf816676bb62726fd1254ef0371849e70ebd2ba9cffb3029d3d68a32643b62927d354328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
